title: "Hanmo Chen's Homepage"
page-top-title: "Hanmo Chen"
top-section-bg-text: "Deep Learning, Computer Vision, AIGC, LLM"
home-subtitle: "Hanmo Chen | 陈翰墨"
copyright-text: "© Hanmo Chen 2023–2025. All Rights Reserved."
social_links:
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/AlexDoe"
  - label: "Google Scholar"
    icon: "ai ai-google-scholar"
    url: "https://scholar.google.com/citations?user=XXXX"
  - label: "Email"
    icon: "fas fa-envelope"
    url: "mailto:alex.doe@example.com"
